env:
   global:
     - CONAN_USERNAME: "francescalted"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/blosc/Conan"
     - CONAN_REMOTES: "https://api.bintray.com/conan/blosc/Conan"
     - CONAN_ARCHS: "x86,x86_64"

linux: &linux
   os: linux
   sudo: false
   dist: trusty
   language: python
   python: "3.6"
osx: &osx
   os: osx
   language: generic

matrix:
   include:
      - <<: *linux
        compiler: gcc

      - <<: *osx
        compiler: clang
        osx_image: xcode8.3

install:
  - bash scripts/install.sh

script:
   - bash scripts/run.sh
