# AppVeyor CI build configuration for c-blosc

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "Visual Studio 12 Win64" ..
  - cmd: cmake --build . --config Release

test_script:
  - cmd: cmake --build . --config Release --target test
